build:
    environment:
        timezone: 'Europe/Zurich'
        php:
            version: '7.2'
            ini:
                'date.timezone': 'Europe/Zurich'
            pecl_extensions:
                - swoole
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage/clover.xml'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'php-clover'

checks:
    php: true

coding_style:
    php: {}

filter:
    excluded_paths:
        - 'tests/*'
